spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: admin

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: liquibase