spring:
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis
    redis:
      time-to-live: 600000

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  error:
    include-stacktrace: never
    include-message: always
  port: 8080


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG