spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 600000
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  error:
    include-stacktrace: never